import type { SourceCandidate } from "@/lib/techstars/exporter-types";

// Maintained entries are discovery seeds, not trust bypasses. Every page still
// passes host, year, attribution, participant-assertion, and bounded extraction.
export const OFFICIAL_TECHSTARS_SOURCES: readonly SourceCandidate[] = [
  {
    url: "https://www.techstars.com/newsroom/the-2025-class-of-the-abn-amro-techstars-future-of-finance-accelerator",
    origin: "catalog",
    sourceKindHint: "cohort_roster",
    acceleratorYearHint: 2025,
    acceleratorBatchHint: "ABN AMRO + Techstars Future of Finance Accelerator",
    strategyHints: ["participant_list", "company_cards"],
    expectedMinimumCompanies: 1,
  },
  {
    url: "https://www.techstars.com/newsroom/transforming-the-future-of-work-techstars-announces-2025-workforce",
    origin: "catalog",
    sourceKindHint: "cohort_roster",
    acceleratorYearHint: 2025,
    acceleratorBatchHint: "Techstars Workforce Development Accelerator 2025",
    strategyHints: ["participant_list", "company_cards"],
    expectedMinimumCompanies: 1,
  },
  {
    url: "https://www.techstars.com/newsroom/welcoming-the-2025-class-of-the-techstars-transformative-world-torino",
    origin: "catalog",
    sourceKindHint: "cohort_roster",
    acceleratorYearHint: 2025,
    acceleratorBatchHint: "Techstars Transformative World Torino 2025",
    strategyHints: ["participant_list", "company_cards"],
    expectedMinimumCompanies: 1,
  },
  {
    url: "https://www.techstars.com/newsroom/announcing-the-techstars-web3-class-of-2025",
    origin: "catalog",
    sourceKindHint: "cohort_roster",
    acceleratorYearHint: 2025,
    acceleratorBatchHint: "Techstars Web3 Accelerator 2025",
    strategyHints: ["participant_list", "company_cards"],
    expectedMinimumCompanies: 1,
  },
  {
    url: "https://www.techstars.com/newsroom/announcing-techstars-anywhere-2025-spring-class",
    origin: "catalog",
    sourceKindHint: "cohort_roster",
    acceleratorYearHint: 2025,
    acceleratorBatchHint: "Techstars Anywhere Spring 2025",
    strategyHints: ["participant_list", "company_cards"],
    expectedMinimumCompanies: 1,
  },
  {
    url: "https://www.techstars.com/newsroom/announcing-the-techstars-london-2025-cohort",
    origin: "catalog",
    sourceKindHint: "cohort_roster",
    acceleratorYearHint: 2025,
    acceleratorBatchHint: "Techstars London Spring 2025",
    strategyHints: ["participant_list", "company_cards"],
    expectedMinimumCompanies: 1,
  },
  {
    url: "https://www.techstars.com/newsroom/techstars-ai-health-baltimore-2025-class-announcement",
    origin: "catalog",
    sourceKindHint: "cohort_roster",
    acceleratorYearHint: 2025,
    acceleratorBatchHint: "Techstars AI Health Baltimore Spring 2025",
    strategyHints: ["participant_list", "company_cards"],
    expectedMinimumCompanies: 1,
  },
  {
    url: "https://www.techstars.com/newsroom/meet-the-startups-joining-techstars-spring-2026-accelerator-programs",
    origin: "catalog",
    sourceKindHint: "cohort_roster",
    acceleratorYearHint: 2026,
    acceleratorBatchHint: "Techstars Spring 2026 Accelerator Programs",
    strategyHints: ["participant_list", "company_cards"],
    expectedMinimumCompanies: 1,
  },
  {
    url: "https://www.techstars.com/blog/impact/techstars-update-june-2025",
    origin: "catalog",
    sourceKindHint: "announcement",
    acceleratorYearHint: 2025,
    acceleratorBatchHint: "Techstars portfolio update",
    strategyHints: ["participant_list", "spotlight_sections"],
    expectedMinimumCompanies: 1,
  },
  {
    url: "https://www.techstars.com/newsroom/meet-the-techstars-nyc-spring-2026-class",
    origin: "catalog",
    sourceKindHint: "cohort_roster",
    acceleratorYearHint: 2026,
    acceleratorBatchHint: "Techstars NYC Spring 2026",
    strategyHints: ["participant_list", "company_cards"],
    expectedMinimumCompanies: 1,
  },
] as const;
