import type { SourceCandidate } from "@/lib/masschallenge/exporter-types";

// Maintained entries are discovery seeds, not trust bypasses. Every page still
// passes host, year, attribution, participant-assertion, and bounded extraction.
export const OFFICIAL_MASSCHALLENGE_SOURCES: readonly SourceCandidate[] = [
  {
    url: "https://masschallenge.org/news/switzerland-2025-accelerator-cohort/",
    origin: "catalog",
    sourceKindHint: "cohort_roster",
    acceleratorYearHint: 2025,
    acceleratorBatchHint: "MassChallenge Switzerland 2025 Early-Stage Accelerator",
    strategyHints: ["participant_list", "company_cards"],
    expectedApproximateCompanies: 103,
  },
  {
    url: "https://masschallenge.org/news/masschallenge-uk-2025-cohort/",
    origin: "catalog",
    sourceKindHint: "cohort_roster",
    acceleratorYearHint: 2025,
    acceleratorBatchHint: "MassChallenge UK 2025 Early-Stage Accelerator",
    strategyHints: ["participant_list", "company_cards"],
    expectedApproximateCompanies: 41,
  },
  {
    url: "https://masschallenge.org/news/the-future-of-fintech-starts-here-meet-the-2025-masschallenge-fintech-cohort/",
    origin: "catalog",
    sourceKindHint: "cohort_roster",
    acceleratorYearHint: 2025,
    acceleratorBatchHint: "MassChallenge FinTech 2025",
    strategyHints: ["known_structured_data", "company_cards", "participant_list"],
    expectedApproximateCompanies: 12,
  },
  {
    url: "https://masschallenge.org/news/masschallenge-announces-2025-air-force-labs-cohort-bridging-commercial-innovation-and-defense/",
    origin: "catalog",
    sourceKindHint: "cohort_roster",
    acceleratorYearHint: 2025,
    acceleratorBatchHint: "MassChallenge Air Force Labs Accelerator 2025",
    strategyHints: ["known_structured_data", "participant_list", "company_cards"],
    expectedApproximateCompanies: 12,
  },
  {
    url: "https://masschallenge.org/news/masschallenge-and-smore-works-announce-top-10-finalists-for-the-2025-constellation-program/",
    origin: "catalog",
    sourceKindHint: "cohort_roster",
    acceleratorYearHint: 2025,
    acceleratorBatchHint: "MassChallenge Constellation Program 2025",
    strategyHints: ["participant_list", "company_cards"],
    expectedApproximateCompanies: 10,
  },
  {
    url: "https://masschallenge.org/news/introducing-the-bae-systems-deep-tech-accelerator-cohort-where-dual-use-innovation-meets-real-world-impact/",
    origin: "catalog",
    sourceKindHint: "partner_program",
    acceleratorYearHint: 2025,
    acceleratorBatchHint: "BAE Systems Deep-Tech Accelerator 2025",
    strategyHints: ["participant_list", "company_cards"],
    expectedApproximateCompanies: 3,
  },
  {
    url: "https://masschallenge.org/articles/from-earth-observation-to-off-world-innovation-meet-the-startups-selected-for-the-deloitte-commercial-space-challenge/",
    origin: "catalog",
    sourceKindHint: "partner_program",
    acceleratorYearHint: 2025,
    acceleratorBatchHint: "Deloitte Commercial Space Challenge 2025",
    strategyHints: ["participant_list", "spotlight_sections"],
    expectedApproximateCompanies: 3,
  },
  {
    url: "https://masschallenge.org/news/masschallenge-switzerland-food-security-prize-2025/",
    origin: "catalog",
    sourceKindHint: "partner_program",
    acceleratorYearHint: 2025,
    acceleratorBatchHint: "MassChallenge Switzerland Food Security Prize 2025",
    strategyHints: ["participant_list", "company_cards"],
    expectedApproximateCompanies: 7,
  },
  {
    url: "https://masschallenge.org/news/masschallenge-selects-17-startups-for-the-social-impact-ventures-program/",
    origin: "catalog",
    sourceKindHint: "cohort_roster",
    acceleratorYearHint: 2025,
    acceleratorBatchHint: "MassChallenge Impact Ventures 2025",
    strategyHints: ["participant_list", "company_cards"],
    expectedApproximateCompanies: 17,
  },
] as const;
